# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
settings:
  name: vscode-go
  min_similarity: 0.8
  repos:
    - https://github.com/golang/vscode-go

  # Who should automatically be considered a project member?
  # See: https://developer.github.com/v4/enum/commentauthorassociation/
  # Default is "collaborator, owner, member", unless "members" is set
  #
  #member-roles:
  # - collaborator
  # - owner
  # - member
  # Who else do we consider to be a project member? Default is empty.
  #members:
  # - tstromberg

collections:
  - id: daily
    name: Daily Triage
    dedup: true
    description: >
      queue to be emptied once a day
    rules:
      - issue-needs-response
      - issue-waiting-for-info
  
  - id: triage-recap
    name: Triage Recap
    dedup: true
    description: >
      Issues from the last week
    rules:
      - issue-updated-last-7days

rules:

  issue-needs-response:
    name: "Needs response"
    resolution: "Add to milestone"
    type: issue
    filters:
      - label: "WaitingForInfo"
      - tag: author-last
      - tag: recv
      - tag: recv-q
  
  issue-waiting-for-info:
    name: "Unactionable issues"
    resolution: "None"
    type: issue
    filters:
      - label: "WaitingForInfo"

  issue-updated-last-7days:
    name: "Issues touched in the last 7 days"
    resolution: "None"
    type: issue
    filters:
      - updated: -7d